Tensorflow **Basic**

In [1]:
import os 
import tensorflow as tf
import cProfile

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[2.]]
m = tf.matmul(x,x)
print('hello, {}'.format(m))

hello, [[4.]]


In [4]:
y = [[4.]]
n = tf.matmul(y,y)
print('{}'.format(n))

[[16.]]


In [5]:
a = tf.constant([[1,2,3],
                [4,5,6]])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
b = tf.add(a, 1)
print(a)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
print(a * b)

tf.Tensor(
[[ 2  6 12]
 [20 30 42]], shape=(2, 3), dtype=int32)


In [8]:
x1 = tf.constant([1,2,3,4,5])
x2 = tf.constant([7,8,9,10,11])

results = tf.multiply(x1,x2)
print(results)

tf.Tensor([ 7 16 27 40 55], shape=(5,), dtype=int32)


In [9]:
x3 = tf.constant([[1,2], [3,4], [5,6], [7,8], [9,10]])
x4 = tf.constant([[11,12], [13,14], [15,16], [17,18], [19,20]])

In [10]:
print(x3)
print(x4)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]], shape=(5, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]], shape=(5, 2), dtype=int32)


In [11]:
results_1 = tf.multiply(x3,x4)
print(results_1)

tf.Tensor(
[[ 11  24]
 [ 39  56]
 [ 75  96]
 [119 144]
 [171 200]], shape=(5, 2), dtype=int32)


In [12]:
concat = tf.concat(values=[x3,x4], axis=0)
print(concat)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]], shape=(10, 2), dtype=int32)


In [13]:
concat_1 = tf.concat(values=[x3,x4], axis=1)
print(concat_1)

tf.Tensor(
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]
 [ 9 10 19 20]], shape=(5, 4), dtype=int32)


In [15]:
zero_matrix = tf.zeros(shape=[4,5], dtype=tf.int32)
print(zero_matrix)

tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(4, 5), dtype=int32)


In [17]:
unit_matrix = tf.ones(shape=[4,5], dtype=tf.int32)
print(unit_matrix)

tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(4, 5), dtype=int32)


In [18]:
reshape_matrix = tf.reshape(tensor=concat, shape=[20,1])
print(reshape_matrix)

tf.Tensor(
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]], shape=(20, 1), dtype=int32)


In [20]:
intx4_to_float = tf.cast(x4, tf.float32)
print(intx4_to_float)

tf.Tensor(
[[11. 12.]
 [13. 14.]
 [15. 16.]
 [17. 18.]
 [19. 20.]], shape=(5, 2), dtype=float32)
